# Generated by Django 4.2.6 on 2024-12-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot_epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epreuve', models.FileField(upload_to='epreuves/')),
                ('corrige_type', models.FileField(upload_to='corriges/')),
                ('niveau', models.CharField(max_length=100)),
            ],
        ),
    ]
