# Generated by Django 4.2.6 on 2024-12-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_depot_epreuve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot_epreuve',
            name='niveau',
            field=models.CharField(max_length=255),
        ),
    ]
