# Generated by Django 4.2.6 on 2024-12-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_depot_epreuve_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajout_annee_pastorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=255)),
            ],
        ),
    ]
