# Generated by Django 4.2.6 on 2024-12-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ajout_annee_pastorale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee_pastorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=255)),
                ('statut', models.CharField(default='inactif', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Ajout_annee_pastorale',
        ),
    ]
