# Generated by Django 4.2.6 on 2025-01-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cotisation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cotisation',
            new_name='Cotisation_Enfant',
        ),
    ]
