# Generated by Django 4.2.6 on 2025-01-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_cotisation_cotisation_enfant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation_Animateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
