# Generated by Django 4.2.6 on 2025-01-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cotisation_animateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cotisation_Animateur',
        ),
    ]
