# Generated by Django 4.2.6 on 2025-01-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cotisation_animateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cotisation_Animateur',
        ),
        migrations.DeleteModel(
            name='Cotisation_Enfant',
        ),
    ]
