# Generated by Django 4.2.6 on 2025-01-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cotisation_animateur_cotisation_enfant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=10)),
                ('annee', models.CharField(max_length=255)),
            ],
        ),
    ]
