# Generated by Django 4.2.6 on 2025-01-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='caisse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='depense',
            name='motif',
            field=models.CharField(max_length=1000),
        ),
    ]
