# Generated by Django 4.2.6 on 2025-01-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_depense_caisse_alter_depense_motif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('annee', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.CharField(max_length=1000)),
            ],
        ),
    ]
