# Generated by Django 4.2.6 on 2025-01-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_penalite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ancien_Solde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=255)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
