# Generated by Django 4.2.6 on 2025-01-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_ancien_solde'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontantCalcule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cotisations', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_benefices', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_penalites', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_depenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nouveau_solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
