# Generated by Django 4.2.6 on 2025-01-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_objectif_tg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectif_tg',
            name='objectif',
            field=models.CharField(max_length=5000),
        ),
    ]
