# Generated by Django 4.2.6 on 2025-01-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_objectif_tg_objectif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objectif_TG',
        ),
    ]
