# Generated by Django 4.2.6 on 2025-01-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_objectif_og'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=5000)),
                ('annee', models.CharField(max_length=255)),
            ],
        ),
    ]
