# Generated by Django 4.2.6 on 2025-01-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_bilan_activite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan_activite',
            name='activite',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='bilan_activite',
            name='effectif',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan_activite',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
