# Generated by Django 4.2.6 on 2025-01-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_point_activite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancien_solde',
            name='solde',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='benefice',
            name='montant',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bilan_activite',
            name='effectif',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bilan_activite',
            name='montant',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cotisation_animateur',
            name='montant',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cotisation_enfant',
            name='montant',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='montantcalcule',
            name='ancien_solde',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='montantcalcule',
            name='nouveau_solde',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='montantcalcule',
            name='total_benefices',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='montantcalcule',
            name='total_cotisations',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='montantcalcule',
            name='total_depenses',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='montantcalcule',
            name='total_penalites',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='penalite',
            name='montant',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='point_activite',
            name='benefice',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='point_activite',
            name='effectif',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='point_activite',
            name='montant',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='point_activite',
            name='perte',
            field=models.CharField(max_length=500),
        ),
    ]
