# Generated by Django 4.2.6 on 2025-01-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_ancien_solde_solde_alter_benefice_montant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MontantCalcule',
        ),
    ]
