# Generated by Django 4.2.6 on 2025-01-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_delete_montantcalcule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontantCalcule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_solde', models.CharField(max_length=500)),
                ('total_cotisations', models.CharField(max_length=500)),
                ('total_benefices', models.CharField(max_length=500)),
                ('total_penalites', models.CharField(max_length=500)),
                ('total_depenses', models.CharField(max_length=500)),
                ('nouveau_solde', models.CharField(max_length=500)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('annee', models.CharField(max_length=255)),
            ],
        ),
    ]
