# Generated by Django 4.2.6 on 2025-01-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_montantcalcule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
