# Generated by Django 4.2.6 on 2025-01-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectif_SG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectif', models.CharField(max_length=5000)),
                ('annee', models.CharField(max_length=255)),
            ],
        ),
    ]
