# Generated by Django 4.2.6 on 2025-01-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_objectif_sg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant_Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activite', models.CharField(max_length=700)),
                ('nom', models.CharField(max_length=500)),
                ('prenom', models.CharField(max_length=500)),
                ('niveau', models.CharField(max_length=500)),
                ('annee', models.CharField(max_length=255)),
            ],
        ),
    ]
