# Generated by Django 4.2.6 on 2025-01-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_participant_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('prenom', models.CharField(max_length=500)),
                ('age', models.CharField(max_length=700)),
                ('niveau', models.CharField(max_length=500)),
                ('niveau_etude', models.CharField(max_length=700)),
                ('catechese', models.CharField(max_length=700)),
                ('annee', models.CharField(max_length=255)),
            ],
        ),
    ]
