# Generated by Django 4.2.6 on 2025-01-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_enfant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point_Activite',
        ),
    ]
