# Generated by Django 4.2.6 on 2025-01-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Depot_epreuve',
        ),
    ]
