# Generated by Django 4.2.6 on 2025-01-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_depot_epreuve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Depot_epreuve',
        ),
    ]
