# Generated by Django 4.2.6 on 2025-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_depot_epreuve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectif_FO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectif', models.CharField(max_length=5000)),
                ('annee', models.CharField(max_length=255)),
            ],
        ),
    ]
