# Generated by Django 4.2.6 on 2025-01-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classement_reveillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=500)),
                ('heure1', models.CharField(max_length=500)),
                ('ap1', models.CharField(max_length=700)),
                ('as1', models.CharField(max_length=700)),
                ('pc1', models.CharField(max_length=700)),
                ('ce1_1', models.CharField(max_length=700)),
                ('ce2_1', models.CharField(max_length=700)),
                ('th1', models.CharField(max_length=700)),
                ('na1', models.CharField(max_length=700)),
                ('heure2', models.CharField(max_length=500)),
                ('ap2', models.CharField(max_length=700)),
                ('as2', models.CharField(max_length=700)),
                ('pc2', models.CharField(max_length=700)),
                ('ce1_2', models.CharField(max_length=700)),
                ('ce2_2', models.CharField(max_length=700)),
                ('th2', models.CharField(max_length=700)),
                ('na2', models.CharField(max_length=700)),
                ('annee', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Classement_veillee_noel',
        ),
        migrations.DeleteModel(
            name='Classement_veillee_nouvel_an',
        ),
    ]
