# Generated by Django 4.2.6 on 2025-01-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_classement_reveillon_delete_classement_veillee_noel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classement_reveillon',
        ),
    ]
