# Generated by Django 4.2.6 on 2025-01-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_classement_reveillon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classement_triduum_pascal',
            old_name='ap2_samedi_saint',
            new_name='ap_samedi_saint',
        ),
        migrations.RenameField(
            model_name='classement_triduum_pascal',
            old_name='as2_samedi_saint',
            new_name='as_samedi_saint',
        ),
        migrations.RenameField(
            model_name='classement_triduum_pascal',
            old_name='na2_samedi_saint',
            new_name='na_samedi_saint',
        ),
        migrations.RenameField(
            model_name='classement_triduum_pascal',
            old_name='pc2_samedi_saint',
            new_name='pc_samedi_saint',
        ),
        migrations.RenameField(
            model_name='classement_triduum_pascal',
            old_name='samedi_saint_heure2',
            new_name='samedi_saint_heure',
        ),
        migrations.RenameField(
            model_name='classement_triduum_pascal',
            old_name='th2_samedi_saint',
            new_name='th_samedi_saint',
        ),
    ]
