# Generated by Django 4.2.6 on 2025-01-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_rename_ap2_samedi_saint_classement_triduum_pascal_ap_samedi_saint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classement_fete',
            old_name='ce1_fete',
            new_name='heure',
        ),
        migrations.RemoveField(
            model_name='classement_fete',
            name='ce2_fete',
        ),
    ]
