# Generated by Django 4.2.6 on 2025-01-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_delete_classement_semaine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classement_semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.CharField(max_length=500)),
                ('date_fin', models.CharField(max_length=500)),
                ('ap_lun_6h30', models.CharField(max_length=700)),
                ('as_lun_6h30', models.CharField(max_length=700)),
                ('ap_lun_19h00', models.CharField(max_length=700)),
                ('as_lun_19h00', models.CharField(max_length=700)),
                ('mar_heure', models.CharField(max_length=700)),
                ('ap_mar', models.CharField(max_length=700)),
                ('as_mar', models.CharField(max_length=700)),
                ('mer_heure', models.CharField(max_length=700)),
                ('ap_mer', models.CharField(max_length=700)),
                ('as_mer', models.CharField(max_length=700)),
                ('ap_jeu_6h30', models.CharField(max_length=700)),
                ('as_jeu_6h30', models.CharField(max_length=700)),
                ('ven_heure', models.CharField(max_length=700)),
                ('ap_ven', models.CharField(max_length=700)),
                ('as_ven', models.CharField(max_length=700)),
                ('ap_sam_6h30', models.CharField(max_length=700)),
                ('as_sam_6h30', models.CharField(max_length=700)),
                ('ap_sam_19h00', models.CharField(max_length=700)),
                ('as_sam_19h00', models.CharField(max_length=700)),
                ('pc_sam_19h00', models.CharField(max_length=700)),
                ('ap_dim_6h30', models.CharField(max_length=700)),
                ('as_dim_6h30', models.CharField(max_length=700)),
                ('pc_dim_6h30', models.CharField(max_length=700)),
                ('ap_dim_8h00', models.CharField(max_length=700)),
                ('as_dim_8h00', models.CharField(max_length=700)),
                ('pc_dim_8h00', models.CharField(max_length=700)),
                ('ap_dim_9h30', models.CharField(max_length=700)),
                ('as_dim_9h30', models.CharField(max_length=700)),
                ('pc_dim_9h30', models.CharField(max_length=700)),
                ('ap_dim_18h00', models.CharField(max_length=700)),
                ('as_dim_18h00', models.CharField(max_length=700)),
                ('pc_dim_18h00', models.CharField(max_length=700)),
                ('annee', models.CharField(max_length=255)),
            ],
        ),
    ]
