# Generated by Django 4.2.6 on 2025-01-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_signature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signature',
        ),
    ]
